# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11GZ_ZmTfu6BKUfHm7t6jyNpKBbVRQATD
"""

import requests
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import os

# --- 1. API Data Retrieval and Storage ---
def task_1():
# Here I am using Open Search Library API because it is public and doesn't need any API keys. It is best suited for this assingment.
# Here extracting data related to Python Programming books and set the limit as 10
    url = "https://openlibrary.org/search.json?q=python+programming&limit=10"

    try:
        response = requests.get(url)
        data = response.json()

        # Extracting specific attributes for assingment requirements
        books = []
        for work in data.get('docs'):
            title = work.get('title')
            author = work.get('author_name', ['Unknown'])[0] # ensuring to extract only one author name
            year = work.get('first_publish_year', 'N/A')
            books.append((title, author, year))

        # SQLite Storage
        conn = sqlite3.connect('Task_1.db') # creating and connecting database file
        cursor = conn.cursor()
        cursor.execute('DROP TABLE IF EXISTS books') # Ensuring not to have duplicates and fresh start
        cursor.execute('''CREATE TABLE books
                          (title TEXT, author TEXT, pub_year TEXT)''')

        cursor.executemany('INSERT INTO books VALUES (?, ?, ?)', books) # inserting entire list at a time
        conn.commit()

        print(f"Successfully stored books in SQLite.")

        cursor.execute("SELECT * FROM books") # dislaying the fetched data
        rows = cursor.fetchall()

        for row in rows:
            print(row)
        conn.close()

    except Exception as e:
        print(f"Error in Task 1: {e}")


# --- 2. Data Processing and Visualization (Student Scores) ---
def task_2():

    # Mocking the API response format.Since I don't have any API key for this type of data
    api_response = [
        {"name": "Ananya", "score": 85},
        {"name": "Ishaan", "score": 92},
        {"name": "Abdul", "score": 78},
        {"name": "Riya", "score": 88},
        {"name": "Kabir", "score": 95},
        {"name": "Mohammad", "score": 95},
        {"name": "Das", "score": 75},
        {"name": "Surya", "score": 60},
        {"name": "Kevin", "score": 68}
        ]

    names = [s['name'] for s in api_response]
    scores = [s['score'] for s in api_response]
    avg_score = sum(scores) / len(scores)
    print(f"The average score of the students is {avg_score}")

    # Plotting
    plt.figure(figsize=(10, 6))
    plt.bar(names, scores, color='skyblue', edgecolor='navy')
    plt.axhline(y=avg_score, color='red', linestyle='--', label=f'Average: {avg_score:.2f}') # using a dotted line to classify students by avg_score

    plt.xlabel('Student Name')
    plt.ylabel('Test Score')
    plt.title('Student Test Performance Analysis')
    plt.legend() # used to make the chart interactive

    plt.savefig('student_analysis.png') # Saving chart as .png file
    plt.show()


# --- 3. CSV Data Import to Database ---
def task_3():

    # Creating a CSV file
    data = {
    'Name' : ['John','Ravi','Sameer','Surya','Lavanya'],
    'Email' : ['John@gmail.com','Ravi@gmail.com','Sameer@gmail.com','Surya@gmail.com','Lavanya@gmail.com']
    }

    pd.DataFrame(data).to_csv('Users.csv', index = False)

    # Reading CSV and Inserting to sqlite3 database
    df = pd.read_csv('Users.csv')
    conn = sqlite3.connect('Task_3.db')

    # to_sql is the most efficient way to handle this in Python
    df.to_sql('users', conn, if_exists='replace', index=False)

    print(f"Imported {len(df)} rows from CSV to 'users' table.")
    conn.close()


if __name__ == "__main__":
    # Execute all tasks
    task_1()
    task_2()
    task_3()
    print("\n--- All assignment tasks completed successfully! ---")